### ISSUE TITLE
Instanzeigene Namespaces für Sessions einrichten

### ISSUE THREAD

**Issue by torstenroeder** [torstenroeder/zefiro#1]
Bei Verwendung mehrerer Instanzen auf einem Client kann es zu Verwirrungen kommen (z.B. plötzlicher Logout), da die Flotilla-Session immer gleich benannt ist.

**Comment by Rillke** [comment]
Does this issue refer to the name of the session cookie? If not, could you describe more detailed what the problem is?

**Comment by torstenroeder** [comment]
Closed. Appears only under circumstances when the same session name is defined in the config file AND if the system is running on the same PHP instance.
