### ISSUE TITLE
Missing constants

### ISSUE THREAD

**Issue by Rillke** [torstenroeder/zefiro#14]
Some constants aren't defined in the default config, nor is there a hint that they should be defined.

* DBI_DATABASE_STATUS
* DBI_ADMIN
* DBI_DATABASE
* Z_SEPARATOR_SYMBOL
* Z_BREADCRUMB_SYMBOL

**Comment by torstenroeder** [comment]
They should be imported from the translation files.

**Comment by torstenroeder** [comment]
It should actually not occur that one of these is used before a translation set is loaded.

**Comment by Rillke** [comment]
A search, e.g. for [DBI_DATABASE_STATUS](https://github.com/torstenroeder/zefiro/search?q=DBI_DATABASE_STATUS&unscoped_q=DBI_DATABASE_STATUS) only returns use of those constants but no definitions. Where are the language files supposed to live in? Do they have to be created by the server admin?

**Comment by torstenroeder** [comment]
I have replaced the prefix DBI by Z (DBI was deprecated).

**Comment by torstenroeder** [comment]
Where does Z_SEPARATOR_SYMBOL occur?

**Comment by Rillke** [comment]
> Where does Z_SEPARATOR_SYMBOL occur?

689920201e919e46 accidentally added that constant to `custom/config.default.php`

**Comment by Rillke** [comment]
I notice there are still `DBI_` constants defined in [custom/config.default.php](/torstenroeder/zefiro/blob/master/custom/config.default.php).

**Comment by torstenroeder** [comment]
this should work much better now. L_ => localization constants, Z_ => zefiro system constants. we should consider some more prefixes to make it clearer.

**Comment by torstenroeder** [comment]
If any constant is missing, it can be done as quickfix. Closed.
