### ISSUE TITLE
Fix 9ffbc8d54

### ISSUE THREAD

**Issue by Rillke** [torstenroeder/zefiro#24]
Commit 9ffbc8d54 introduced some bugs by

1. deleting ending RegExp delims
2. not declaring intended usage of parent-scope variables in anonymous functions

Additionally, we might want work against HTML injection / CWE-79 Type 2: Stored XSS (or Persistent), dependent on whether the CMS defines the database contents as HTML or not and which promises it wants to make to its users.
`$row->{$matches[2]}` should be probably be `htmlspecialchars($row->{$matches[2]},ENT_HTML5)`

**Comment by Rillke** [comment]
Actually, commit 1b97c49de7dab37224221c60c4783883bc76c94d (#29) will fix 1. and 2.

I thought there is more broken but it doesn't appear to.

**Comment by torstenroeder** [comment]
I think this can be closed?
