### ISSUE TITLE
Passwort-Hashing in Nutzertabelle

### ISSUE THREAD

**Issue by torstenroeder** [torstenroeder/zefiro#7]

**Comment by Rillke** [comment]
There is a function in PHP, called [`password-hash`](http://php.net/manual/de/function.password-hash.php), made for this use case.

**Comment by torstenroeder** [comment]
Oh right, I see that the API contains the function you mentioned.

**Comment by torstenroeder** [comment]
set new password should either become a separate procedure (not within edit_user) and should somehow be integrated in the flotilla framework.
